name: Sync voXSim remote repository

# GitHub App/Action mirror-repository: https://github.com/yesolutions/mirror-action

on:
  push:
    branches:
      - master

jobs:
  sync_mirror_repo:
    runs-on: ubuntu-latest

    environment:
      name: MIRRORING

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"
          fetch-depth: 0

      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: "${{ secrets.VOXSIM_REMOTE }}"
          GIT_SSH_PRIVATE_KEY: ${{ secrets.VOXSIM_SSH_PRIVATE_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.VOXSIM_SSH_KNOWN_HOSTS }}
